=== joberiai/Devour-Hope/Devour-Hope/src/xml/ganadores.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ganadores (ganador+)> 

<!ELEMENT ganador (nombre, numVictorias)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numVictorias (#PCDATA)>

=== joberiai/Devour-Hope/Devour-Hope/src/xml/ranking.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ganadores SYSTEM "ganadores.dtd" >
<ganadores>
  <ganador>
    <nombre>Jota</nombre>
    <numVictorias>5</numVictorias>
  </ganador>
  
  <ganador>
    <nombre>Mamá</nombre>
    <numVictorias>4</numVictorias>
  </ganador>
  
  <ganador>
    <nombre>Bea</nombre>
    <numVictorias>3</numVictorias>
  </ganador>
  
  <ganador>
    <nombre>Papá</nombre>
    <numVictorias>1</numVictorias>
  </ganador>
</ganadores>
